---
- name: Sample IOS playbook to run show commands
  hosts: iosxe
  gather_facts: no

  tasks:
    - name: Run show ip int brief
      cisco.ios.ios_command:
        commands: show ip interface brief
      register: myinterfaces
    - name: Display my interfaces
      debug:
        var: myinterfaces.stdout_lines[0]

    - name: Run show users
      cisco.ios.ios_command:
        commands: show users
      register: myusers
    - name: Display my users
      debug:
        var: myusers.stdout_lines[0]


    