---
- name: CONSUME SDWAN API WITH uri MODULE
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: GET AUTH COOKIE WITH POST REQUEST
      uri:
        url: "https://{{ inventory_hostname }}/j_security_check"
        method: POST
        body_format: form-urlencoded
        body:
          j_username: "{{ username }}"
          j_password: "{{ password }}"
        validate_certs: no
        return_content: yes
      register: post_response
    - name: PRINT RESULT
      debug:
        var: post_response
    - name: SAVE SESSION COOKIE IN A VARIABLE
      set_fact:
        vmanage_cookie: "{{ post_response.set_cookie }}"
    - name: PRINT SAVED COOKIE
      debug:
        var: vmanage_cookie

    - name: PAUSE FOR 3 SECONDS
      pause:
        seconds: 1

    - name: GET LIST OF FABRIC DEVICES
      uri:
        url: "https://{{ inventory_hostname }}/dataservice/system/device/vedges"
        method: GET
        headers:
          Cookie: "{{ vmanage_cookie }}"
        validate_certs: no
        return_content: yes
      register: devices_list
    - name: PRINT_LIST_OF_DEVICES1
      debug:
        var: devices_list.json.data
    - name: PRINT_LIST_OF_DEVICES
      debug:
        # var: item
        msg: "{{ item['name'] }} {{ item['system-ip'] }}"  # message to print for each item, must use bracket notation due to -
      with_items: "{{ devices_list.json.data }}"  # this becomes the 'item'
      loop_control:
        label: "{{ item.serialNumber }}"  # print serial number as a label
      when: "'name' in item"  # only print if 'name' key exists, skip otherwise

    # - name: COLLECT LIST OF DEVICE IPS
    #   with_items: "{{ devices_list.json.data }}"

    - name: SET INTERESTING DEVICE ID
      set_fact:
        # 0 or 1 or 9 in this lab
        deviceId: "{{ devices_list.json.data[1].deviceIP }}"




- name: Check SELECTED DEVICE
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: GET REBOOT HISTORY DETAILS
      uri:
        url: "https://{{ inventory_hostname }}/dataservice/device/reboothistory?deviceId={{ deviceId }}"
        method: GET
        headers:
          Cookie: "{{ vmanage_cookie }}"
        validate_certs: no
        return_content: yes
      register: reboot_history
    - name: PRINT_REBOOT_HISTORY
      debug:
        var: reboot_history.json.data

    - name: GET VPN TUNNEL STATS
      uri:
        url: "https://{{ inventory_hostname }}\
          /dataservice/device/tunnel/statistics?deviceId={{ deviceId }}"
        method: GET
        headers:
          Cookie: "{{ vmanage_cookie }}"
        validate_certs: no
        return_content: yes
      register: tunnel_stats
    - name: PRINT TUNNEL STATISTICS
      debug:
        var: tunnel_stats.json.data

    - name: GET DEVICE SYSTEM STATUS
      uri:
        url: "https://{{ inventory_hostname }}\
          /dataservice/device/system/status?deviceId={{ deviceId }}"
        method: GET
        headers:
          Cookie: "{{ vmanage_cookie }}"
        validate_certs: no
        return_content: yes
      register: device_status
    - name: PRINT DEVICE STATUS INFO
      debug:
        # var: device_status
        msg: "Hostname: {{ device_status.json.data[0]['vdevice-host-name'] }} | \
          CPU System: {{ device_status.json.data[0]['cpu_system'] }} | \
          CPU User: {{ device_status.json.data[0]['cpu_user'] }} | \
          RAM Used: {{ device_status.json.data[0]['mem_used'] }} | \
          Disk Used: {{ device_status.json.data[0]['disk_used'] }}\
          "
    - name: GET ROUTING TABLE DETAILS
      uri:
        url: "https://{{ inventory_hostname }}\
          /dataservice/device/ip/routetable?deviceId={{ deviceId }}"
        method: GET
        headers:
          Cookie: "{{ vmanage_cookie }}"
        validate_certs: no
        return_content: yes
      register: routing_data
    - name: PRINT ROUTING TABLE
      debug:
        var: routing_data.json.data
    - name: PRINT NUMBER OF ROUTES
      debug:
        var: routing_data.json.data | length
        
      


